
AWS_PROFILES="
20min-admin
20min_dev-admin
20min_sandbox-admin
appstream-operator
dai_dev-admin
dai_prod-admin
dai_sandbox-admin
disco-admin
disco_dev-admin
disco_sandbox-admin
mars_dce_prod-admin
ness-admin
pmd_generic-admin
pmd_generic_prod-admin
ta_interaktiv-admin
tamedia_atm-admin
tamedia_backup-admin
tamedia_discovery-admin
tamedia_discovery_dev-admin
tamedia_discovery_sandbox-admin
tamedia_mc_dev-admin
tamedia_mc_prod-admin
tex-admin
titan_dev-admin
titan_prod-admin
unity_demo-admin
unity_dev-admin
unity_preprod-admin
unity_prod-admin
unity_sandbox-admin
unity_staging-admin
"
